### ISSUE TITLE
Questions on how to use the program

### ISSUE THREAD

**Issue by izabala123** [YingyiLiu/HAMS#1]
Dear  Yingyi

I have been trying your software with great interest, and I have some questions and comments:

- When running Certests/Cylinder, the software fails: 

![image](https://user-images.githubusercontent.com/38589221/102520240-c4bca680-4093-11eb-887a-dc41995f59ca.png)

Reading the ControlFile.in it seems like this file version is older.

- It would be great if you would have a simple manual about how to use your software. I have many questions about it:
-- There is always a HullMesh.pnl and a WaterplaneMesh.pnl. What are they for? Could be loaded in Wamit mesh format?
-- Is it compulsory to include Hydrostatic.in, even without trying to get the RAOs?

Best regards
Iñaki

**Comment by YingyiLiu** [comment]
Dear Iñaki,

Thank you very much for your email. Actually I am also using your software
BEMRosetta which has given me a lot of convenience in processing of the
input and output data.

The issue with Cylinder case is my fault, I have already fixed it
just a few minutes ago. That was due to I haven't updated the Cylinder case
input file as well when I upgrade the code. Please try again.

Yes I am planning to write a manual. It may be in the close future days.
But as I am caught up by many other duties, I have not been able to write
the tutorial up to present, I will do that later.

HullMesh.pnl is for the immersed body mesh, and WaterplaneMesh.pnl is for
the waterplane mesh (to remove irregular frequencies).

Yes I have write a WamitMesh converter, which can transform Wamit mesh
format to HAMS mesh format. I will later upload it as well.

Yes, now it seems it is compulsory to include Hydrostatic.in even without
trying to get RAOs. But you can set Hydrostatic with all zeros if you do
not want RAOs calculation. I will refine this part in the future so that
you will not compulsorily input Hydrostatic.

By the way, I am very much interested to collaborate with you if you could
also include HAMS in your BEMRosetta, I believe it will be very helpful to
the open-source community.

Have a nice weekend. Let's keep in contact.

Best regards,
Yingyi

Iñaki Zabala <notifications@github.com> 于2020年12月18日周五 上午2:27写道：

**Comment by izabala123** [comment]
Thank you very much for your interest. I would like to know a little bit about your software to facilitate its access from BEMRosetta. To do this I would like to execute some cases that I have and see their results. One file that I don't know how to obtain is the WaterplaneMesh. I would also like to know the basic parameters well so as not to make mistakes, so I am waiting for your manual and your mesh converter.

**Comment by YingyiLiu** [comment]
Dear Iñaki,

Thank you for your response.
I will prepare the manual in the coming holidays.
These days the university seems to have blocked the GitHub website,
I will upload the mesh converter later at home.

I will inform you when all these things are ready.

Best regards,
Yingyi

Iñaki Zabala <notifications@github.com> 于2020年12月18日周五 下午8:13写道：

**Comment by izabala123** [comment]
Thank you Yingyi. 

I really want to try it out, but I have little time to try and get it up and running on my own, so your guide will be fine with me.

Iñaki

**Comment by izabala123** [comment]
Thank you Yingyi

The new manual you include solves my question. 
We keep in touch.

Iñaki
